import DashboardBody from '../../components/shared/AdminShared/DashboardBody/DashboardBody';
import React from 'react';

export const metadata = {
  title: "OsamaMart -Admin Panel",
  description: "Generated by Tamzid",
};

const Dp = () => {

  return (
   <div>
    <DashboardBody />
   </div>
  );
};

export default Dp;