import React from 'react';

export const metadata = {
    title: "OsamaMart -Login",
    description: "Generated by Tamzid",
  };

const LoginLayout = ({children}) => {
    return (
        <div>
            {children}
        </div>
    );
};

export default LoginLayout;