import Banner from "@/components/shared/Banner/Banner";
import FrequentlyAskedQuestions from "@/components/shared/FrequentlyAskedQuestions/FrequentlyAskedQuestions";
import HomeDetails from "@/components/shared/HomeDetails/HomeDetails";
import OurCategories from "@/components/shared/OurCategories/OurCategories";
import OurLatestNews from "@/components/shared/OurLatestNews/OurLatestNews";
import OurSpecialGallery from "@/components/shared/OurSpecialGallery/OurSpecialGallery";

export const metadata = {
  title: "OsamaMart -Home",
  description: "Generated by Tamzid",
};

const Home = () => {
  return (
    <div className="xl:max-w-7xl lg:max-w-6xl md:max-w-3xl sm: max-w-sm mx-auto mt-16">
      <Banner />
      <OurCategories />
      <OurLatestNews/>
      <OurSpecialGallery/>
      <HomeDetails/>
      <FrequentlyAskedQuestions/>
    </div>
  );
}

export default Home;
