
import Testimonial from "../../components/shared/UserShared/Testimonial/Testimonial.jsx";
import Banner from "../../components/shared/UserShared/Banner/Banner.jsx";
import FrequentlyAskedQuestions from "../../components/shared/UserShared/FrequentlyAskedQuestions/FrequentlyAskedQuestions";
import HomeDetails from "../../components/shared/UserShared/HomeDetails/HomeDetails";
import OurCategories from "../../components/shared/UserShared/OurCategories/OurCategories";
import OurLatestNews from "../../components/shared/UserShared/OurLatestNews/OurLatestNews";
import OurSpecialGallery from "../../components/shared/UserShared/OurSpecialGallery/OurSpecialGallery";

export const metadata = {
  title: "OsamaMart -Home",
  description: "Generated by Tamzid",
};

const Home = () => {
  return (
    <div className="mt-16">
      <Banner />
      <div className="xl:max-w-7xl lg:max-w-6xl md:max-w-3xl sm: max-w-sm mx-auto ">
        <OurCategories />
        <OurLatestNews />
        <OurSpecialGallery />
        <HomeDetails />
        <Testimonial />
        <FrequentlyAskedQuestions />
      </div>
    </div>
  );
}

export default Home;
