'use client' ;
import { baseUrl } from "../../../../utilies/config";
import axios from "axios";
import { useEffect, useState } from "react";

// export const metadata = {
//     title: "OsamaMart -All ProductsDetails",
//     description: "Generated by Tamzid",
//   };



const AllProductsDetails = ({params}) => {

    const [toyDetails, setToyDetails] = useState(null);

    useEffect(() => {
      axios
        .get(baseUrl('all-toys'))
        .then((res) => { const toy = res.data.find((item) => item.id === params.id);
          setToyDetails(toy);})
        .catch((error) => {
            setToyDetails(error);
        });
    }, [params?.id]);
    console.log("toys-data----", toyDetails);

    return (
        <div className="pt-[70px]">
        {params ?
        <>
         <p>{params?.id}</p> 
         <p>{params?.name}</p> 
        </>
         : <p>Loading...</p>}
        </div>
    );
};

export default AllProductsDetails;


