import SingleProductDetails from "../AllProductsCards/SingleProductDetails";

export const metadata = {
  title: "OsamaMart -Products Details",
  description: "Generated by Tamzid",
};

const AllProductsDetails = () => {
  return (
    <div className="mt-[60px]">
      <SingleProductDetails />
    </div>
  );
};

export default AllProductsDetails;


