
export const metadata = {
    title: "OsamaMart -All ProductsDetails",
    description: "Generated by Tamzid",
  };



const AllProductsDetails = ({params}) => {

    const [toyDetails, setToyDetails] = useState([]);

    useEffect(() => {
      axios
        .get(baseUrl("all-toys"))
        .then((res) => setAllToys(res.data))
        .catch((error) => {
            setToyDetails(error);
        });
    }, []);

    return (
        <div className="pt-[70px]">
        {params ? <p>{params.id}</p> : <p>Loading...</p>}
        </div>
    );
};

export default AllProductsDetails;


