export const metadata = {
  title: "OsamaMart -Home",
  description: "Generated by Tamzid",
};

const Home = () => {
  return (
    <div>
    <h1>
      Home
    </h1>
    </div>
  );
}

export default Home;
