import React from 'react';
import PaymentGateway from './PaymentGateway';

export const metadata = {
    title: "OsamaMart -Payment Gateway",
    description: "Generated by Tamzid",
};

const gatewayDiv = () => {
    return (
        <div>
            <PaymentGateway/>
        </div>
    );
};

export default gatewayDiv;