import React from 'react';
import AdminUpdateToys from '../../allToys/AdminUpdateToys/AdminUpdateToys';

export const metadata = {
    title: "OsamaMart -Update Toys",
    description: "Generated by Tamzid",
  };
const updateToysCompo = () => {
    return (
        <div>
            <AdminUpdateToys/>
        </div>
    );
};

export default updateToysCompo;