import React from 'react';
import AdminAddToys from './AdminAddToys/AdminAddToys';
import { kanit } from '../../../utilies/FontsProvider/fontProvider';
import { IoIosArrowForward } from 'react-icons/io';


export const metadata = {
  title: "OsamaMart -Add Toys",
  description: "Generated by Tamzid",
};


const AddToys = () => {
    return (
        <div>
<div className={` ${kanit.className} w-full `}>
                    <h1 className='text-[20px] font-[700] mb-2'>New Toy</h1>
                    <ul className='w-full flex items-center gap-[10px] text-neutral-400 text-[14px] font-[500]'>
                        <li>Dashboard</li>
                        <li><IoIosArrowForward /></li>
                        <li>New Toy</li>
                    </ul>
                </div>
            <AdminAddToys/>
        </div>
    );
};

export default AddToys;