import React from 'react';
import AdminAllToys from '../../../components/shared/AdminShared/AdminAllToys/AdminAllToys';
import { Kanit } from "next/font/google";

const kanit = Kanit({
  weight: ["400", "700"],
  style: ["normal"],
});

export const metadata = {
  title: "OsamaMart -About Us",
  description: "Generated by Tamzid",
};


const AllToys = () => {
    return (
        <div>
            <h1 className={` ${kanit.className} text-3xl text-center`}>All Toys</h1>
            <div className='flex justify-center mt-3'>
            <hr className='w-60'/>
            </div>
            <AdminAllToys />
        </div>
    );
};

export default AllToys;