import React from "react";
import AdminAllToys from "./AdminAllToys/AdminAllToys";
import { kanit } from "./AdminUpdateToys/AdminUpdateToysForm";
import { IoIosArrowForward } from "react-icons/io";
import Link from "next/link";

export const metadata = {
  title: "OsamaMart -All Toys",
  description: "Generated by Tamzid",
};

const AllToys = () => {
  return (
    <div className="">
      <div className={` ${kanit.className} w-full `}>
        <h1 className="text-[20px] font-[900] mb-[8px]">Toys List</h1>
        <ul className="w-full flex items-center gap-[10px] text-neutral-400 text-[14px] font-[500]">
          <li>Dashboard</li>
          <li>
            <IoIosArrowForward />
          </li>
          <li>Toy List</li>
        </ul>
      </div>
      {/* add button  */}
      <div className="flex justify-end">
        <Link className="" href="addToys">
          <button
            className={` ${kanit.className} w-full uppercase border-2 px-4 py-2 font-semibold bg-orange-700 hover:bg-transparent rounded-sm`}
          >
          Add New
          </button>
        </Link>
      </div>
      <AdminAllToys />
    </div>
  );
};

export default AllToys;
