import React from 'react';
import AdminAllToys from './AdminAllToys/AdminAllToys';
import { kanit } from './AdminUpdateToys/AdminUpdateToysForm';
import { IoIosArrowForward } from "react-icons/io";


export const metadata = {
    title: "OsamaMart -All Toys",
    description: "Generated by Tamzid",
};


const AllToys = () => {
    return (
        <div className=''>
                <div className={` ${kanit.className} w-full `}>
                    <h1 className='text-[20px] font-[900] mb-[8px]'>Toys List</h1>
                    <ul className='w-full flex items-center gap-[10px] text-neutral-400 text-[14px] font-[500]'>
                        <li>Dashboard</li>
                        <li><IoIosArrowForward /></li>
                        <li>Toys List</li>
                    </ul>
                </div>
            {/* </div> */}
            <AdminAllToys />
        </div >
    );
};

export default AllToys;